Update mattermost-support.md
infracloudio/botkube pull request #361
Opened 2020-09-30 18:52 UTC by NEERAJAP2001

##### ISSUE TYPE

 
 - Typo fix Pull Request

##### SUMMARY
fixed a typo

2020-10-01 05:24 UTC, PrasadG193 approved these changes

2020-10-01 05:26 UTC, PrasadG193 requested changes

2020-10-01 05:26 UTC, PrasadG193 commented on design/mattermost-support.md
> +- Start a go routine for Mattermost.
I think goroutine should be the single word
Please see: https://gobyexample.com/goroutines

2020-10-01 05:46 UTC, PrasadG193 approved these changes

2020-10-01 05:46 UTC, PrasadG193 commented
Thanks for the PR @NEERAJAP2001. Looking forward to more contributions from you :)

2020-10-01 05:56 UTC, merged

2020-11-10 15:54 UTC, chetanpdeshmukh commented
Hello @NEERAJAP2001 ,
Thanks again for the PR!

Thank you for contributing to BotKube. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdULT22oZlpHPMXKVEtV4fZ6R8vdGDC2iFvMhoG6IhZkK1SFA/viewform?usp=sf_link), so we can send the well deserved awesome swags :slightly_smiling_face:

Team BotKube