Add a support for ignoring the events from a namespace that matches regexp
infracloudio/botkube pull request #386
Opened 2020-10-01 14:54 UTC by jkremser

Fixes issue #295

##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY

This change allows to ignore whole sets of namespaces using the asterix expansion. It still does the exact match check for all the namespaces (separated by comma in config), but if it contains a `*`, it's actually replaced with `.*` and passed to `regexp.MatchString` to do the job.

PR also contains couple of very simple test cases.

deps:
`namespace_checker.go` now imports also `regexp`

Fixes #295

:cookie:

2020-10-01 16:58 UTC, PrasadG193 commented
Awesome! Thanks for the PR @jkremser :pray: 
We should add an e2e test for this. Will file a separate ticket for that

2020-10-01 16:59 UTC, PrasadG193 approved these changes

2020-10-01 17:01 UTC, PrasadG193 requested changes

2020-10-01 22:04 UTC, jkremser commented on pkg/filterengine/filters/namespace_checker.go
> +					matched, _ := regexp.MatchString(ns, eventNamespace)
done + there was also a logical error I've fixed. Returning the `matched` boolean was not correct behavior.

2020-10-02 12:04 UTC, PrasadG193 commented on pkg/filterengine/filters/namespace_checker.go
> +					if matched && err == nil {
```suggestion
					if err == nil && matched {
```

2020-10-02 16:06 UTC, PrasadG193 approved these changes

2020-10-02 16:07 UTC, merged

2020-11-10 15:53 UTC, chetanpdeshmukh commented
Hello @jkremser ,
Thanks again for the PR!

Thank you for contributing to BotKube. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdULT22oZlpHPMXKVEtV4fZ6R8vdGDC2iFvMhoG6IhZkK1SFA/viewform?usp=sf_link), so we can send the well deserved awesome swags :slightly_smiling_face:

Team BotKube