Added badges and fixed punctuation
infracloudio/botkube pull request #387
Opened 2020-10-01 14:59 UTC by sumitkharche

##### ISSUE TYPE
 - Docs Pull Request

##### SUMMARY
- Added license, slack & release badges
- added period at end of sentence

Fixes
- changed in README.md file

2020-10-05 08:03 UTC, bhavin192 requested changes
LGTM, just one minor change.

2020-10-05 08:03 UTC, bhavin192 commented on README.md
> +[![Slack](https://badgen.net/badge/slack/botkube/blue?icon=slack)](http://join.botkube.io/)
```suggestion
[![Slack](https://badgen.net/badge/slack/BotKube/blue?icon=slack)](http://join.botkube.io/)
```

2020-10-05 09:01 UTC, sumitkharche commented on README.md
> +[![Slack](https://badgen.net/badge/slack/botkube/blue?icon=slack)](http://join.botkube.io/)
Done

2020-10-05 09:59 UTC, sanketsudake approved these changes

2020-10-05 10:01 UTC, bhavin192 approved these changes

2020-10-05 10:22 UTC, sumitkharche commented
Thanks @sanketsudake and @bhavin192  for review.

2020-10-06 05:03 UTC, merged

2020-11-10 15:53 UTC, chetanpdeshmukh commented
Hello @sumitkharche ,
Thanks again for the PR!

Thank you for contributing to BotKube. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdULT22oZlpHPMXKVEtV4fZ6R8vdGDC2iFvMhoG6IhZkK1SFA/viewform?usp=sf_link), so we can send the well deserved awesome swags :slightly_smiling_face:

Team BotKube