Passing communications config as a k8s secret using existingSecret
infracloudio/botkube pull request #482
Opened 2021-05-06 09:59 UTC by ebrianne

##### ISSUE TYPE
 - Feature Pull Request

##### SUMMARY
I have implemented in the helm chart the possibility to pass the communication config map as a k8s secret and configure in the value files via an existingSecret. It can be configured in the values file via these:

```yaml
communications:
    existingSecret: false
    existingSecretName: ""
```

Fixes #319 #211 #226 #233

2021-05-13 10:59 UTC, bhavin192 requested changes
Thank you for creating the change, this looks good to me. I have suggested a change related to name of the secret.

2021-05-13 10:59 UTC, bhavin192 commented on helm/botkube/templates/_helpers.tpl
> +{{- default (include "botkube.fullname" .) (.Values.communications.existingSecretName) -}}
I think the default name should be kept what it was before i.e. `{{ include "botkube.fullname" . }}-communication-secret`. That way the name will indicate correctly that it is a communication related secret. Also, we won't break anything if someone is depending on that name to do something (less likely, but still).

2021-05-13 10:59 UTC, bhavin192 commented on helm/botkube/values.yaml
> +  # Communication secret already existing
```suggestion
  # Using existing Communication secret
```

2021-05-14 10:44 UTC, pierluigilenoci commented
@ebrianne could you please implement the suggestion in your PR?

2021-05-14 10:47 UTC, ebrianne commented
I will implemented the changes as soon as I have time... today won't be possible. I ll try over the week end.

2021-05-18 07:54 UTC, pierluigilenoci commented
@ebrianne any news?

2021-05-18 08:35 UTC, ebrianne commented
I have just pushed the suggested changes

2021-05-18 08:43 UTC, pierluigilenoci commented
@bhavin192 could you please take a look?

2021-05-21 13:45 UTC, pierluigilenoci commented
@PrasadG193 could you please take a look?

2021-05-25 08:28 UTC, bhavin192 requested changes

2021-05-25 08:28 UTC, bhavin192 commented on helm/botkube/templates/communicationsecret.yaml
> +{{- if not .Values.communications.existingSecret -}}
```suggestion
{{- if not .Values.communications.existingSecretName -}}
```

How about this?
Right now, if one does following, current logic tries to use the secret even if we have set it to not use it (`false`).
```
 --set communications.existingSecretName="test" --set communications.existingSecret=false
```
With the suggested change we can remove the `existingSecret` value as well.

2021-05-25 09:31 UTC, pierluigilenoci commented
@ebrianne now it's your turn 😜

2021-05-25 09:46 UTC, bhavin192 commented on helm/botkube/values.yaml
> +  existingSecretName: ""
```suggestion
  # Using existing Communication secret
  existingSecretName: ""
```

2021-05-25 11:53 UTC, pierluigilenoci commented
![i8O0J31](https://user-images.githubusercontent.com/36044817/119493489-87ee8d00-bd60-11eb-907a-ba703fa11714.gif)
😆

2021-05-25 12:18 UTC, bhavin192 approved these changes
:tada: :rocket:

2021-05-25 13:03 UTC, merged

2021-06-10 15:34 UTC, onedr0p commented
Please push a new release of the chart this is very much needed 🙏🏼

2021-08-05 17:37 UTC, rhummelmose commented
Why isn't a Helm chart with this released yet?

2021-08-09 15:14 UTC, pierluigilenoci commented
@rhummelmose nope. 😢

2021-08-09 15:14 UTC, pierluigilenoci commented
@bhavin192 @PrasadG193 can you help to make a release?

2021-08-09 16:13 UTC, PrasadG193 commented
Hey @pierluigilenoci, I am already working on it. We will make a release this week. Sorry for the delay.

2021-08-09 19:07 UTC, rhummelmose commented
Thanks, really need this (y)

2021-08-11 14:10 UTC, onedr0p commented
@PrasadG193 could you please also make the GHCR image the default in the chart <3

https://github.com/infracloudio/botkube/pull/498

2021-08-17 10:20 UTC, rhummelmose commented
@PrasadG193 Is this coming? :)

2021-08-17 10:43 UTC, onedr0p commented
What's holding up the release, do you all need help on anything?